id: ID4DDDFD6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:52:11+00:00'
last_modified: '2022-06-07T22:26:54.094496+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4738
  title: རི་ཆོས་གཏམ་ཀུན་ཏུ་བཟང་པོའི་སྒྲ་དབྱངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    68C7:
      image_group_id: I3CN4740
      title: ''
      total_pages: 116
      order: 1
      base_file: 68C7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
