id: P004380
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:16:46.220314
source_metadata:
  id: bdr:W3CN4738
  title: རི་ཆོས་གཏམ་ཀུན་ཏུ་བཟང་པོའི་སྒྲ་དབྱངས།
  author: ''
  volumes:
    bd316bcb5a0045d4aa11b2dae95c8a28:
      image_group_id: I3CN4740
      title: ''
      volume_number: 1
      total_pages: 116
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
