id: P004380
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4738
  title: རི་ཆོས་གཏམ་ཀུན་ཏུ་བཟང་པོའི་སྒྲ་དབྱངས།
  author: ''
  volumes:
    bd316bcb5a0045d4aa11b2dae95c8a28:
      image_group_id: I3CN4740
      title: ''
      volume_number: 1
      total_pages: 116
      base_file: v001.txt
